development:
  adapter: postgresql
  encoding: unicode
  database: theRightBrain_development
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: theRightBrain_test
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: theRightBrain_production
  host: localhost
  port: 5432
